src/Luxor.jl
test/luxor-test1.jl

By ensuring that the surface hasn't been destroyed already before finishing and destroying it. Added test that calling finish twice doesn't cause a segfault.
Side note: Thanks to the creators of this package from this graphics tourist!

Fix #12 (finishing a destroyed surface)

---

src/point.jl

avoid type piracy of extending base functions on base types

add ::Point type constraint to arithmetic on tuples

---

docs/src/assets/examples/make-airport-world-map.jl

Handle was un-exported in this commit:
https://github.com/JuliaGeo/Shapefile.jl/commit/f787fd9ae3787209b114484d842090ed3a26667c

Shapefile.Handle

---

src/Luxor.jl

This seems to operate better with Interact.jl, in the latest version using `preview` seems to remove the manipulators. Using the current proposal, the following works:
```julia
using Luxor
using Interact
function makecircle(r)
d = Drawing(100,100,"test.svg")
origin()
circle(O,r,:stroke)
finish()
return d
end
@manipulate for r in 5:50
makecircle(r)
end
```

Override Base.show to show a drawing in IJulia when it is returned

---

src/animate.jl

Added optional argument to scene type to allow for more complex programatic access in frame construction.
This allows a scene function to generate more complex scenes, such as allowing for a random change between frames of an element.

Add abstract type to scene

---

src/Table.jl
src/drawings.jl

I think there's no need to let user type the file extension if they don't want to when there's one in macro already. 
And it is not intuitive when `size(t)` is supported, but `size(t, 1)`/`size(t, 2)` is not.

Auto add file extension & support `size(x, n)`

---

src/curves.jl

The slope was being calculated with the x-axis and the (O, focus2) line, where it should be the x-axis with the (focus1, focus2) line

Fixed bug in ellipse with two focus

---

src/noise.jl

I just rearranged the flow a bit to remove the extra loops, but @time reports it now has 0 allocations. It can be made shorter by vectorizing, and it'd still be an improvement, but this version is the most performant.

Refactored and optimized _octaves in noise.jl

---

src/drawings.jl

It turns out that IJulia and Juno call `show` _twice_, once with the `image/something` MIME type, and [once with the `text/plain` MIME type](https://github.com/JuliaLang/IJulia.jl/blob/master/src/inline.jl#L37). Strange!
This fix detects that the `text/plain` method is such a second call, and doesn't open a file in that case. It now works in the REPL, Pluto, Jupyter and Juno.
MIME types other than `png` or `svg` open a file in all environments.

IJulia & Juno display fix

---

src/point.jl
test/point-arithmetic.jl

The purpose is a terse initialization of test arrays. Instead of writing:
```
pl = [Point(0, 0), Point(1, 1), Point(2, 0), Point(3, 0), Point(4, 0)]
```
one can write:
```
pl = Point.([(0, 0), (1, 1), (2, 0), (3, 0), (4, 0)])
```

Added convenience constructor

---

src/Luxor.jl

If I see this correctly you currently export functions which don't exist "anymore".
Not sure whether you intend to export `BoxmapTile` but as you exported `Boxmaptile` I just renamed it.

removed some exports and renamed others

---

docs/src/text.md
src/Luxor.jl
src/text.jl
test/text-wrapping.jl

This should work when Cairo releases a new version. So I need to update the Project.toml `compat` section then. 
Maybe @cormullion can give feedback already whether that makes sense.
It seems like this is only working for the "toy" API.

[WIP] get_fontsize

---

src/drawings.jl

Fixes #127. Julia was resolving `:width` and `:height` as being variables defined within Luxor, not user input so they needed to be `esc`'d.

Fix macro hygeine of width and height

---

src/curves.jl
test/basic-test.jl

Fix #131.
* Fix the `NaN` issue.
* Add test for `center3pts`
* Throw warning when a center of circle doesn't exists in Euclid plane.
```julia
julia> using Luxor
julia> Luxor.center3pts(Point(1,1), Point(3,1.0000001), Point(2,0))
(Point(2.0000000000000027, 1.0000000000000027), 1.0000000000000027)
julia> Luxor.center3pts(Point(1,1), Point(3,1), Point(2,0))
(Point(2.0, 1.0), 1.0)
julia> Luxor.center3pts(O, O, O)
┌ Warning: There's no circle which pass Point(0.0, 0.0), Point(0.0, 0.0) and Point(0.0, 0.0).
└ @ Luxor ~/.julia/dev/Luxor/src/curves.jl:70
(Point(0.0, 0.0), 0)
```
Reference for the formula:
[「n+1点を通るn-1次元球面」 "n-1 dimensional sphere which passes given n+1 points"](https://hyrodium.github.io/pdf/#n1%E7%82%B9%E3%82%92%E9%80%9A%E3%82%8Bn-1%E6%AC%A1%E5%85%83%E7%90%83%E9%9D%A2)

Bugfix for center3pts

---

Project.toml
src/Luxor.jl

Before:
Which points here: https://github.com/fonsp/Luxor.jl/blob/229768b73e25b7b37f5088a70a5cb2264019abc9/src/animate.jl#L236
After:
https://user-images.githubusercontent.com/6933510/108211523-0ec21700-712d-11eb-8d01-d8ec01567032.mov

import Base64 to fix gif display

---

src/curves.jl

Center c was not used to compute relative vectors.

Fix error in isarcclockwise

---

CHANGELOG.md
docs/src/explanation/transforms.md
src/Luxor.jl
src/basics.jl
src/drawings.jl
test/runtests.jl
test/strokescale-test.jl

- Add new named parameter "strokescale" to constructor
- Add setstrokescale() and setstrokescale(Bool) functions
- Modify behavior of strokepath and stroke_preserve to delegate
to the appropriate Cairo method based on strokescale setting.

Add support for stroke scaling via Cairo.stroke_transformed

---

src/noise.jl
test/noise-test.jl

I realized that I needed a way to pass in a custom RNG to the initnoise function, so I've added that. Please let me know if you have any thoughts or concerns!

Support noise initialization with any AbstractRNG

---

Project.toml

ImageMagick has largely been supplanted by ImageIO.
I also thought I'd see what you thought about avoiding being
"opinionated" about which specific IO packages are best,
so I moved such dependencies to [extras]. But we could move
such dependencies back to [deps] if you're worried about
providing an out-of-box experience that "just works" without
the user having to choose specific IO package(s).
xrefs:
- https://github.com/JuliaIO/PNGFiles.jl/pull/45
- https://github.com/JuliaIO/FileIO.jl/issues/352

Remove the shackles of ImageMagick

---

src/polygons.jl
test/simplify-polygons.jl

Hi @cormullion ,
I think there is currently a bug in the simplify method. This is my attempt to fix it :smile: 
I've also added a small test case for it which would have failed previously.
The keep list seems to have an off by one error and with broadcasting I think it's a bit simpler to read. Not sure whether there is a use case of calling `douglas_peucker` with start point different to `1` as I think it would be easier to read without the `global_start_index`.

correct implementation of simplify

---

docs/src/tutorial/quickstart.md

`mod1(4, end)` gets the last (not first) value of a four element array

Fixing a typo

---

src/latex.jl

Here is an example:
```julia
d = Drawing(400,200,:svg)
origin(100,50)
fontsize(20)
t = L"$x \in ℕ\cup${$-\infty,\, 0 \, , \infty$}"
text(t)
t = L"y \in 𝒞 \, , \, x \in ℬ \quad \frac{x}{y}"
text(t,Point(0,40))
fontsize(20)
t = L"f ⨟ h"
text(t,Point(0,70))
finish()
d
```

Creating special function to deal with extra chars not present in MathTeXEngine

---

src/basics.jl
test/basic-test.jl

This is a small contribution, but I think it might be quite useful. It overloads the `Base.hcat` and `Base.vcat` to work with figures. So one can easily concatenate figures in Luxor.
I've implemented the two functions and a set of tests.
Here is an example. 
```julia
d1 = Drawing(200,100,:svg)
origin()
circle(O,60,:fill)
finish()
d2 = Drawing(200,200,:svg)
rect(O,200,200,:fill)
finish()
hcat(d1,d2; hpad=10, valign=:top, clip = true)
```

New `hcat` and `vcat` for drawings

---

docs/src/assets/luxor-docs.css
docs/src/example/examples.md
docs/src/howto/animation.md
docs/src/howto/colors-styles.md
docs/src/howto/createdrawings.md
docs/src/howto/polygons.md
docs/src/howto/text.md
src/Boxmaptile.jl
src/Turtle.jl
src/basics.jl
src/colors_styles.jl
src/drawings.jl
src/mesh.jl
src/polygons.jl
src/text.jl
test/boxmaptest.jl
test/get_path.jl
test/get_path_flat.jl
test/heart-julia.jl
test/matrix-tests.jl
test/point-inside-polygon.jl
test/polygon-centroid-sort-test.jl
test/polygon-test.jl
test/sierpinski-svg.jl
test/sierpinski.jl
test/simplify-polygons.jl
test/text-path-clipping.jl
test/tiling-images.jl
test/turtle-test.jl

This PR replaces characters `"\t"` and `"'\U00A0'"` with normal white spaces. (x-ref https://github.com/JuliaGraphics/Luxor.jl/pull/209#discussion_r825274761)
**Before this PR**
http://juliagraphics.github.io/Luxor.jl/dev/howto/createdrawings/#Using-Pluto
**After this PR**

Fix spacings in scripts

---

.github/workflows/ci.yml
Project.toml
src/Luxor.jl
src/polygons.jl
test/runtests.jl

`v1.6` is the latest LTS version, so I thought it would be better to replace `1.3` with `1.6`.

Drop support versions of Julia under `v1.6`

---

src/point.jl
test/point-arithmetic.jl

This PR fixes #221.
```julia
julia> using Luxor
julia> zero(Point)
Point(0.0, 0.0)
julia> zero(Point(1,2))
Point(0.0, 0.0)
julia> zeros(Point, 4)
4-element Vector{Point}:
Point(0.0, 0.0)
Point(0.0, 0.0)
Point(0.0, 0.0)
Point(0.0, 0.0)
julia> iszero(O)
true
julia> iszero(Point(1,2))
false
```

Add methods to `Base.zero`

---

Project.toml
src/drawings.jl
src/precompile.jl

This pull request migrates the package from [SnoopPrecompile](https://github.com/timholy/SnoopCompile.jl/tree/master/SnoopPrecompile) to [PrecompileTools](https://github.com/JuliaLang/PrecompileTools.jl).
PrecompileTools is **nearly a drop-in replacement** except that there are **changes in naming and how developers locally disable precompilation** (to make their development workflow more efficient). These changes are described in [PrecompileTool's enhanced documentation](https://julialang.github.io/PrecompileTools.jl/stable/), which also includes instructions for users on how to set up custom "Startup" packages, handling precompilation tasks that are not amenable to workloads, and tips for troubleshooting.
Why the new package? It meets several goals:
- The name "SnoopPrecompile" was …

Migrate from SnoopPrecompile to PrecompileTools

---

src/precompile.jl

With Luxor v3.7.0 I see
```
(@v1.9) pkg> precompile
Precompiling project...
165 dependencies successfully precompiled in 481 seconds. 304 already precompiled.
1 dependency had warnings during precompilation:
┌ Luxor [ae8d54c2-7ccd-5906-9d76-62fc9837b5bc]
│  [ Info: SnoopPrecompile is analyzing Luxor.jl code...
└
```
Note: SnoopPrecompile has been miograted to PrecompileTools in https://github.com/JuliaGraphics/Luxor.jl/pull/263 , but there has not been a release.
I suggest removing the line
```
@info "PrecompileTools is analyzing Luxor.jl code..."
```
from https://github.com/JuliaGraphics/Luxor.jl/blob/master/src/precompile.jl

Remove precompile info to prevent precompile warning

---

src/curves.jl

This PR fixes https://github.com/JuliaGraphics/Luxor.jl/issues/268.
* The number of control points still depends on the radius of the circle. For example, `circle(Point(0,0), 500)` consists of eight Beziser segments. (Before this PR, it was six segments)
* This is because Cairo divides the target arcs into Bezier segments based on some `atol`.
* I think the best way is adding `atol` and `rtol` to `Luxor.circle` as keyword arguments and approximate the target circle in this package. But I'm not sure that kind of flexibility is desired.
* Some other functions such as `pie` and `arc2r` still have the precision issue.
* Checking the precision of the circle would be complicated, so I have not added tests for this change.

Divide a circle into four arcs for more precision

---

.github/workflows/ci.yml
Project.toml
appveyor.yml
ext/LuxorExt.jl
ext/LuxorExtLatex.jl
ext/latex.jl
src/Luxor.jl
src/placeholders_for_extensions.jl
test/latex.jl

modified:   Project.toml
modified:   appveyor.yml
new file:   ext/LuxorExt.jl
renamed:    src/latex.jl -> ext/latex.jl
modified:   src/Luxor.jl
Ref. issue #275. Also, KristofferC [talking](https://youtu.be/TiIZlQhFzyk?t=738), and his [template](https://github.com/KristofferC/PGFPlotsX.jl) with a few extra bells:

Move from @require to v1.9 Ext

---

src/polygons.jl
test/polysmooth-tests.jl

```julia
using Luxor
@drawsvg begin
background("white")
polysmooth([Point(0, 0), Point(0, 100), Point(100, 100), Point(100, 0)], 5, :stroke; close=false)
end 300 300
```

Add keyword argument `close` to function polysmooth

---

src/point.jl
src/polygons.jl

This PR fixes the following two bugs.
1. The polysmooth has one extra line connecting to it.
2. The `intersectlinepoly` can not find intersection in some corner case.

Fix intersect lines and polysmooth function

---

src/bezierpath.jl

This is a slight performance improvement, but it would be better to avoid `Any[]` in the constructor.
**Before this PR**
```julia
julia> using Luxor, BenchmarkTools
julia> @benchmark BezierPath()
BenchmarkTools.Trial: 10000 samples with 981 evaluations.
Range (min … max):  64.005 ns …  3.877 μs  ┊ GC (min … max): 0.00% … 95.72%
Time  (median):     66.467 ns              ┊ GC (median):    0.00%
Time  (mean ± σ):   74.230 ns ± 79.459 ns  ┊ GC (mean ± σ):  4.55% ±  4.48%
▃██▆▃▂▁▁  ▁▆▆▄▂▁                                            ▂
█████████▇█████████▇▇▇▇▇▆▇▇▅▆▆▆▆▇▇█▇▇▇▇▆▆▆▅▆▄▄▅▅▄▆▅▄▄▅▄▄▄▃▄ █
64 ns        Histogram: log(frequency) by time       119 ns <
Memory estimate: 112 bytes, allocs estimate: 3.
```
**After this PR**
```julia
julia> using Luxor, BenchmarkTools
julia> @benchmark …
```

Update `BezierPath` constructor

---

src/bezierpath.jl
src/point.jl

Some `jldoctest` were replaced with `julia` in https://github.com/JuliaGraphics/Luxor.jl/commit/5fc74172c17a951b8e089c9b5ee1368230bb8aff. This PR replaces `julia` with `julia-repl`.

Use `julia-repl` code block

---

src/point.jl

`!=`, `>`, `cmp` are defined in Base, so we don't need to define the methods in Luxor.jl.

Remove unnecessary methods defined in Base
